const allsongs = [
  {
    title: "$orries",
    artist: "Peachy!",
    album: " Shiloh",
    track: "$orries",
    year: "1",
    img_src: "../songs_images/$orries_Cover.jpg",
    src: "./songs/$orries.mp3",
  },
  {
    title: "[oops]",
    artist: "potsu",
    album: "[oops]",
    track: "1",
    year: "",
    img_src: "../songs_images/[oops]_Cover.jpg",
    src: "./songs/[oops].mp3",
  },
  {
    title: "5:32pm",
    artist: "The Deli",
    album: "Vibes 2",
    track: "12",
    year: "",
    img_src: "../songs_images/5_32pm_Cover.jpg",
    src: "./songs/5_32pm.mp3",
  },
  {
    title: "88 Keys",
    artist: "Oatmello",
    album: "Snapshots",
    track: "3",
    year: "",
    img_src: "../songs_images/88_Keys_Cover.jpg",
    src: "./songs/88_Keys.mp3",
  },
  {
    title: "Affection",
    artist: "Jinsang",
    album: "Life",
    track: "15",
    year: "",
    img_src: "../songs_images/Affection_Cover.jpg ",
    src: "./songs/Affection.mp3",
  },
  {
    title: "Again",
    artist: "Wun Two",
    album: "Penthouse",
    track: "4",
    year: "",
    img_src: "../songs_images/Again_Cover.jpg",
    src: "./songs/Again.mp3",
  },
  {
    title: "Alone and Lonely",
    artist: "prxz",
    album: " Shiloh Dynasty",
    track: "Love Wounds",
    year: "2",
    img_src: "../songs_images/Alone_and_Lonely_Cover.jpg",
    src: "./songs/Alone_and_Lonely.mp3",
  },
  {
    title: "Baby You're Worth It",
    artist: "Kina",
    album: "Baby You're Worth It",
    track: "1",
    year: "",
    img_src: "../songs_images/Baby_You're_Worth_It_Cover.jpg",
    src: "./songs/Baby_You're_Worth_It.mp3",
  },
  {
    title: "Backpack City",
    artist: "Flovry",
    album: " tender spring",
    track: "Ages Ago",
    year: "4",
    img_src: "../songs_images/ ",
    src: "./songs/Backpack_City.mp3",
  },
  {
    title: "Beauty",
    artist: "eyeroze",
    album: "Heartless",
    track: "4",
    year: "",
    img_src: "../songs_images/Beauty_Cover.jpg",
    src: "./songs/Beauty.mp3",
  },
  {
    title: "Better Than He Can",
    artist: "Jennifer Flores",
    album: " Shiloh Dynasty",
    track: " LofiCentral",
    year: "All My Love",
    img_src: "../songs_images/Better_Than_He_Can_Cover.jpg",
    src: "./songs/Better_Than_He_Can.mp3",
  },
  {
    title: "Break My Heart Again",
    artist: "90degrees",
    album: "Break My Heart Again",
    track: "1",
    year: "",
    img_src: "../songs_images/Break_My_Heart_Again_Cover.jpg",
    src: "./songs/Break_My_Heart_Again.mp3",
  },
  {
    title: "Brightness",
    artist: "eyeroze",
    album: "Heartless",
    track: "15",
    year: "",
    img_src: "../songs_images/Brightness_Cover.jpg",
    src: "./songs/Brightness.mp3",
  },
  {
    title: "Call me",
    artist: "90sFlav",
    album: "Collection",
    track: "1",
    year: "",
    img_src: "../songs_images/Call_me_Cover.jpg",
    src: "./songs/Call_me.mp3",
  },
  {
    title: "Can We Kiss Forever?",
    artist: "Kina",
    album: " Adriana Proenza",
    track: "Can We Kiss Forever?",
    year: "1",
    img_src: "../songs_images/Can_We_Kiss_Forever_Cover.jpg",
    src: "./songs/Can_We_Kiss_Forever.mp3",
  },
];

export default allsongs;
